[versions]

kotlin = "2.2.20-RC"
compose = "1.9.0-beta03"
hotReload = "1.0.0-beta05"

[libraries]


[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload" }
